package io.github.totomika.pocketmcp.ui.theme

import androidx.compose.ui.graphics.Color

// ── Deep Teal palette (light) ──
val md_primary_light = Color(0xFF006A6A)
val md_onPrimary_light = Color(0xFFFFFFFF)
val md_primaryContainer_light = Color(0xFF6FF0EF)
val md_onPrimaryContainer_light = Color(0xFF002020)
val md_secondary_light = Color(0xFF4A6363)
val md_onSecondary_light = Color(0xFFFFFFFF)
val md_secondaryContainer_light = Color(0xFFCCE8E7)
val md_onSecondaryContainer_light = Color(0xFF051F1F)
val md_tertiary_light = Color(0xFF4B6074)
val md_onTertiary_light = Color(0xFFFFFFFF)
val md_tertiaryContainer_light = Color(0xFFCDE3FA)
val md_onTertiaryContainer_light = Color(0xFF041C2C)
val md_error_light = Color(0xFFBA1A1A)
val md_onError_light = Color(0xFFFFFFFF)
val md_errorContainer_light = Color(0xFFFFDAD6)
val md_onErrorContainer_light = Color(0xFF410002)
val md_background_light = Color(0xFFFAFDFC)
val md_onBackground_light = Color(0xFF191C1C)
val md_surface_light = Color(0xFFFAFDFC)
val md_onSurface_light = Color(0xFF191C1C)
val md_surfaceVariant_light = Color(0xFFDAE5E3)
val md_onSurfaceVariant_light = Color(0xFF3F4948)
val md_outline_light = Color(0xFF6F7978)
val md_outlineVariant_light = Color(0xFFBEC9C7)

// ── Deep Teal palette (dark) ──
val md_primary_dark = Color(0xFF4CDADA)
val md_onPrimary_dark = Color(0xFF003737)
val md_primaryContainer_dark = Color(0xFF004F50)
val md_onPrimaryContainer_dark = Color(0xFF6FF0EF)
val md_secondary_dark = Color(0xFFB1CCCB)
val md_onSecondary_dark = Color(0xFF1B3534)
val md_secondaryContainer_dark = Color(0xFF324B4A)
val md_onSecondaryContainer_dark = Color(0xFFCCE8E7)
val md_tertiary_dark = Color(0xFFB2C8DE)
val md_onTertiary_dark = Color(0xFF1B3144)
val md_tertiaryContainer_dark = Color(0xFF33475B)
val md_onTertiaryContainer_dark = Color(0xFFCDE3FA)
val md_error_dark = Color(0xFFFFB4AB)
val md_onError_dark = Color(0xFF690005)
val md_errorContainer_dark = Color(0xFF93000A)
val md_onErrorContainer_dark = Color(0xFFFFDAD6)
val md_background_dark = Color(0xFF191C1C)
val md_onBackground_dark = Color(0xFFE0E3E2)
val md_surface_dark = Color(0xFF191C1C)
val md_onSurface_dark = Color(0xFFE0E3E2)
val md_surfaceVariant_dark = Color(0xFF3F4948)
val md_onSurfaceVariant_dark = Color(0xFFBEC9C7)
val md_outline_dark = Color(0xFF889392)
val md_outlineVariant_dark = Color(0xFF3F4948)